server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: C:/promtail/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: error_log
    static_configs:
      - targets: [localhost]
        labels:
          job: error_log
          __path__: C:/Users/joeun/Desktop/workspace/Game/MainServer/logs/error.log

  - job_name: game_log
    static_configs:
      - targets: [localhost]
        labels:
          job: game_log
          __path__: C:/Users/joeun/Desktop/workspace/Game/MainServer/logs/game.log

  - job_name: perf_log
    pipeline_stages:
      - json:
          expressions:
            event: event
            msg: msg
            thread_id: thread_id
            timestamp: timestamp
            index: data.index
            recv: data.recv
      - labels:
          event:
    static_configs:
      - targets: [localhost]
        labels:
          job: perf_log
          __path__: C:/Users/joeun/Desktop/workspace/Game/MainServer/logs/perf.log

  - job_name: system_log
    static_configs:
      - targets: [localhost]
        labels:
          job: system_log
          __path__: C:/Users/joeun/Desktop/workspace/Game/MainServer/logs/system.log
